#        _________                                  __ __________        __   
#       /   _____/__ ________ ______   ____________/  |\______   \ _____/  |_ 
#       \_____  \|  |  \____ \\____ \ /  _ \_  __ \   __\    |  _//  _ \   __\
#       /        \  |  /  |_> >  |_> >  <_> )  | \/|  | |    |   (  <_> )  |  
#      /_______  /____/|   __/|   __/ \____/|__|   |__| |______  /\____/|__|  
#              \/      |__|   |__|                             \/             
#
#                      SupportBot version 6.2
#                      Erstellt von Emerald Services
#                      Installiert unter MIT License
#
#                      Support Server: discord.gg/jspKFcE

# Generelle Bot Konfiguration

Token: "BOT_TOKEN_HERE"
Prefix: "-"
Bot_Name: "SupportBot"

BotActivity: "-help | SupportBot"
StreamingURL: "https://www.twitch.tv/YOUR_TWITCH_NAME"
# ActivityType muss auf STREAMING gesetzt werden, damit die Streaming-URL im Bot-Status funktioniert
ActivityType: "PLAYING"
# Der Aktivitätsstatus kann entweder PLAYING, WATCHING, LISTENING oder STREAMING sein.

DeleteMessages: "true"

# Embed Konfiguration

EmbedColour: "#04b545"
EmbedFooter: "SupportBot | Der #1 Support Discord Bot"

ErrorColour: "#d12519"
SuccessColour: "#04b545"
WarningColour: "#fca117" 

# Rollen Konfiguration

AutoRole: "true"
# Wenn Sie "AutoRole" auf "true" setzen, vergibt der Bot automatisch die folgende Rolle, wenn Mitglieder deinem Discord Server beitreten. Setze dies auf "false", um diese Funktion zu deaktivieren. 
AutoRole_Role: "Member"
LockdownRole: "@everyone"

Staff: "Staff"
Admin: "Admin"

# Ticket Konfiguration

TicketChannel: "ticket"
TicketCategory: "Tickets"
TicketLog: "ticket-logs"
TranscriptLog: "transcripts"
TicketSubject: "description"
# TicketSubject: "description" bedeutet, dass der Grund des Tickets in der Kanalbeschreibung steht, "embed" bedeutet, dass der Grund im Embed steht.

AllowTicketMentions: "true"
# Setze dies auf "true" damit das Ticket den Ersteller und das Support-Team pingt.
# Setze dies auf "false" um Pings in Tickets zu deaktivieren


# Ticket Panel (Per Reaktion ein Ticket erstellen)

ReactionTickets: "true"
ReactionMessage: "Reagiere mit %reaction_emoji% um ein Ticket zu erstellen!"
ReactionPanel_Description: "true"
ReactionDescription: "Erstellen Sie ein Support-Ticket, um einen Mitarbeiter zu kontaktieren."
ReactionChannel: "create-ticket"
ReactionEmoji: "📩"
# Custom Emojis: <:test:EMOJI_ID>
ReactionPanel_Thumbnail: "true"
ReactionThumbnail: "https://hotemoji.com/images/dl/5/ticket-emoji-by-twitter.png"

Ticket_Thumbnail: "https://images.emojiterra.com/google/android-pie/512px/1f39f.png"
Ticket_Title: "Server Support | %ticketusername%"
TicketMessage: "Hallo <@%ticketauthor%>, Vielen Dank das du ein Ticket erstellt hast\nBitte warte, bis sich ein Mitglied unseres Teams meldet!"
NoTicketSubject: "Keinen Grund angegeben!"
TicketCreatedAlert: ":ticket: Dein Ticket wurde erstellt: <#%ticketid%>"
TranscriptTitle: "Ticket Transcript"

AddedUser: "👍 <@%user%> wurde zu dem Ticket hinzugefügt"
RemovedUser: "👍 <@%user%> wurde aus dem Ticket entfernt"

ClosingTicket: ":warning: Du hast angefragt, dein Ticket zu schließen"
ClosingConfirmation_Word: "confirm"
CloseConfirmation: "true"
# CloseConfirmation "true" erwartet von Usern eine Bestätigung zum schließen des Ticket, setze dies auf "false" damit das Ticket einfach geschlossen wird.

# Ticket Abteilungskonfiguration

TicketDepartments: "true"
# Diese Option aktiviert oder deaktiviert die verschiedenen Ticket Abteilungen, setze dies auf "false" um keine Ticket Abteilungen zu haben.

AllowStaff: "true"
# Allowstaff ist eine Option welche der Rolle "Staff" ermöglicht, im Ticket mitzulesen, setze dies auf "false" damit die Rolle "Staff" nicht mitlesen kann.

DepartmentEmoji_1: "🙋"
DepartmentEmoji_2: "💸"
DepartmentEmoji_3: "📗"
# Ticket Emojis, auf welche die User reagieren um ein Ticket für die verschiedenen Abteilungen zu erstellen, natürlich nur wenn die Abteilungen aktiviert sind.

DepartmentTitle_1: "Support"
DepartmentTitle_2: "Billing"
DepartmentTitle_3: "Other"
# Ticket Abteilungstitel, dies ist der Titel einer Ticketabteilung, um Nutzern zu helfen, damit diese wissen welche Abteilungen vorhanden sind.

DepartmentRole_1: "Support"
DepartmentRole_2: "Admin"
DepartmentRole_3: "Support"
# Ticketrollen sind die Rollen, welche abhängig von der Abteilung Zugriff auf Tickets erhalten.

# System Nachrichten Konfiguration

SystemMessages: "true"

SystemMessage_Channel: "System-Nachrichten"
SystemMessage_Type: "embed"
# Es gibt 2 Arten wie Sie System Nachrichten senden können, "normal" oder "embed"
SystemMessage_Icon: "USER"

Welcome_Title: "User hat den Server betreten!"
WelcomeMessage: "Herzlich Willkommen %member%, Willkommen auf %guildname%!"
# %member% definiert den Nutzer welcher gerade gejoint ist, %guildnamne% den Server Namen.

Leave_Title: "User hat den Server verlassen!"
LeaveMessage: "Es war schön dich zu sehen %member%, Danke dir für den Besuch auf %guildname%!"
# %member% definiert den Nutzer, welcher den Server verlassen hat, %guildname% den Server Namen.

SystemMessage_EmbedFooter: "false"

# LINKS Konfiguration

LinksTitle: "Quick Links"

LINKS:
  "Website": "https://www.example.com"
  "Store": "https://store.example.com"
  "Discord": "https://discord.gg/example"
# "Twitter": "https://twitter.com/example"

# Suggestions Konfiguration

SuggestionChannel: "suggestions"
SuggestionTitle: "Suggestion"
SuggestionStarter: "Was möchtest du vorschlagen?"
SuggestReact_1: 👍
SuggestReact_2: 👎

# Announcement Konfiguration

AnnouncementChannel: "announcements"
AnnouncementTitle: "Servername Announcement"
AnnouncementIcon: "https://i.imgur.com/HbkZyB7.png"

AnnouncementStarter: "Was möchtest du ankündigen?"

# General Command Konfiguration

HelpCommand: "help"
LinksCommand: "links"
PingCommand: "ping"
SuggestCommand: "suggest"

# Support Command Konfiguration

NewTicket: "ticket"
CloseTicket: "close"
AddUser: "add"
RemoveUser: "remove"
RenameTicket: "rename"

# Staff Command Konfiguration
BotSay: "say"

# Admin Command Konfiguration

AnnounceCommand: "announce"

# Commmand Beschreibungen (help)

NewTicketDesc: "Erstelle ein neues Support Ticket"
AnnounceDesc: "Erstelle eine neue Server Ankündigung"
CloseTicketDesc: "Schließe dein Support Ticket"
LinksDesc: "Zeigt wichtige Links an"
PingDesc: "Bekomme die Bot Latenz"
HelpDesc: "Erhalte eine Liste der verfügbaren Befehle"
RemoveUserDesc: "Entferne einen Nutzer aus einem Ticket"
AddUserDesc: "Füge einen Nutzer einem Ticket hinzu"
SuggestionDesc: "Erstelle einen Server Vorschlag"
BotSayDesc: "Sage etwas mit dem Bot"

# Error / Warning Nachrichten

IncorrectPerms: ":x: **Error!** Du hast nicht die benötigten Berechtigungen um diesen Befehl auszuführen."
InvalidChannel: ":x: **Error!** Channel nicht gefunden. Bitte erstelle diesen Channel!"
UserNotFound: ":x: **Error!** Dieser Nutzer existiert nicht, ist er auf diesem Server?"
NoValidTicket: ":warning: Du kannst diesen Befehl hier nicht verwenden. Dieser Befehl wird zum schließen eines Tickets verwendet."
TicketExists: ":warning: Dieses Ticket kann nicht erstellt werden, es existiert bereits."
